// Auto-generated by: npx supabase gen types typescript --linked
// Run after every migration to regenerate. Do not edit manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          full_name: string | null;
          role: "worker" | "manager";
          created_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          role?: "worker" | "manager";
          created_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          role?: "worker" | "manager";
          created_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      users_active: {
        Row: {
          id: string;
          full_name: string | null;
          role: "worker" | "manager";
          created_at: string;
          deleted_at: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      is_manager: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
    };
    Enums: {
      user_role: "worker" | "manager";
      order_status: "NEW" | "IN_PROGRESS" | "ON_HOLD" | "READY" | "DELIVERED";
      debt_type: "WHOLESALE" | "RETAIL";
      product_type: "METER" | "UNIT";
    };
    CompositeTypes: Record<PropertyKey, never>;
  };
};
